# -*- coding: utf-8 -*-
"""amazon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/adrian-spataru/stdm/blob/master/amazon.ipynb

# Amazon Book Dataset

Dataset on Amazon's Top 50 bestselling books from 2009 to 2019. Contains 550 books, data has been categorized into fiction and non-fiction using Goodreads.

The Columns are self-explanatory.

Optionally, if you want to do some string manipulation, you can checkout:
https://pandas.pydata.org/pandas-docs/stable/user_guide/text.html
"""

"""# Libs"""
import pandas as pd
import numpy as np
import seaborn as sns

import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
import matplotlib
plt.style.use('ggplot')
from matplotlib.pyplot import figure

"""# Data Preprocessing"""
df = pd.read_csv("goodreads_amazon.csv")

def data_set_info(dataFrame):
    print("Head:")
    print(dataFrame.head())
    print('-' * 70 + "\nShape:")
    print(dataFrame.shape)
    print('-' * 70 + "\nDatatypes:")
    print(dataFrame.dtypes)


def print_missing_percentage(dataFrame):
    print('-' * 70 + "\nMissing Data in %:")
    for col in dataFrame.columns:
        per_missing = np.mean(dataFrame[col].isnull())
        print('{} - {}%'.format(col, round(per_missing * 100)))


data_set_info(dataFrame=df)
print_missing_percentage(dataFrame=df)
print(df.describe())




